/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterFace;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import models.Account;
import MySQL.ConnectSQL;
import models.Customer;

/**
 *
 * @author PC
 */
public class RegisterForm extends javax.swing.JFrame {

    ConnectSQL cn = new ConnectSQL();

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        doFill();
    }

    private void doFill() {
        panel_CardLayout.removeAll();;
        panel_CardLayout.add(jPanel1);
        panel_CardLayout.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_CardLayout = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        txt_Password = new javax.swing.JPasswordField();
        txt_PassConfirm = new javax.swing.JPasswordField();
        btn_Cancel1 = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CbxGender = new javax.swing.JComboBox<>();
        txt_Address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_MobileNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_Cancel2 = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        txt_Email = new javax.swing.JTextField();
        jdate_DateOfBirthC = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        panel_CardLayout.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("User Registration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Confirm");

        txt_UserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_UserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_UserNameKeyPressed(evt);
            }
        });

        txt_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PasswordKeyPressed(evt);
            }
        });

        txt_PassConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PassConfirmKeyPressed(evt);
            }
        });

        btn_Cancel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Cancel1.setText("Cancel");
        btn_Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel1ActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(255, 255, 255));
        btn_Next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Next.setText("Next");
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Cancel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel3)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Password)
                            .addComponent(txt_UserName)
                            .addComponent(txt_PassConfirm))))
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_PassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancel1)
                    .addComponent(btn_Next))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        panel_CardLayout.add(jPanel1, "card2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Other Information");

        CbxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select.....", "Male", "Female", "Other" }));

        txt_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AddressKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email ID");

        txt_MobileNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_MobileNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MobileNumberKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mobile Number");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date Of Birth");

        btn_Cancel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Cancel2.setText("Cancel");
        btn_Cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancel2ActionPerformed(evt);
            }
        });

        btn_Save.setBackground(new java.awt.Color(255, 255, 255));
        btn_Save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_EmailKeyPressed(evt);
            }
        });

        jdate_DateOfBirthC.setDateFormatString("yyyy-MM-dd");
        jdate_DateOfBirthC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CbxGender, 0, 238, Short.MAX_VALUE)
                                    .addComponent(txt_Address)
                                    .addComponent(txt_MobileNumber)
                                    .addComponent(jdate_DateOfBirthC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(88, 88, 88)
                                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_Cancel2)
                        .addGap(134, 134, 134)
                        .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jdate_DateOfBirthC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_MobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Save)
                    .addComponent(btn_Cancel2))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        panel_CardLayout.add(jPanel2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_CardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_CardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_Cancel1ActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed

        String user, pass, confirmPass;
        boolean checkFill = true;
        boolean checkSamePass = true;

        user = txt_UserName.getText();
        pass = String.valueOf(txt_Password.getPassword());
        confirmPass = String.valueOf(txt_PassConfirm.getPassword());

        if (user.equals("")) {
            txt_UserName.setBorder(BorderFactory.createLineBorder(Color.RED));
            checkFill = false;
        }

        if (pass.equals("")) {
            txt_Password.setBorder(BorderFactory.createLineBorder(Color.RED));
            checkFill = false;
        }

        if (confirmPass.equals("")) {
            txt_PassConfirm.setBorder(BorderFactory.createLineBorder(Color.RED));
            checkFill = false;
        }

        if (!checkFill) {
            JOptionPane.showMessageDialog(this, "Please Fill in All");
            return;
        }

        boolean checkUser = doCheckAccount(user);

        if (!checkUser) {
            JOptionPane.showMessageDialog(this, "This username has already been used");
            return;
        }

        if (!confirmPass.equals(pass)) {
            checkSamePass = false;
        }

        if (!checkSamePass) {
            JOptionPane.showMessageDialog(this, "The password doesn't match");
            return;
        }

        panel_CardLayout.removeAll();;
        panel_CardLayout.add(jPanel2);
        panel_CardLayout.updateUI();
    }//GEN-LAST:event_btn_NextActionPerformed

    private boolean doCheckAccount(String userR) {
        ArrayList<Account> listAccount = cn.getListAccount();

        for (int i = 0; i < listAccount.size(); i++) {
            if (listAccount.get(i).getUsername().equals(userR)) {
                return false;
            }
        }

        return true;
    }
    private void btn_Cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancel2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_Cancel2ActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        String email, gender, phoneNumber, address;
        boolean checkFill = true;

        email = txt_Email.getText();
        gender = (String) CbxGender.getSelectedItem();
        phoneNumber = txt_MobileNumber.getText();
        address = txt_Address.getText();

        if (email.equals("")) {
            txt_Email.setBorder(BorderFactory.createLineBorder(Color.RED));
            checkFill = false;
        }

        if (phoneNumber.equals("")) {
            txt_MobileNumber.setBorder(BorderFactory.createLineBorder(Color.RED));
            checkFill = false;
        }

        if (address.equals("")) {
            txt_Address.setBorder(BorderFactory.createLineBorder(Color.RED));
            checkFill = false;
        }

        if (!checkFill) {
            JOptionPane.showMessageDialog(this, "Please Fill in All");
            return;
        }

        if (gender.equalsIgnoreCase("select.....")) {
            JOptionPane.showMessageDialog(this, "Choose 'Other' if you do not want to reveal your gender!");
            return;
        }

        try {
            Long.parseLong(phoneNumber);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid phone Number");
            return;
        }

        doAddUser();
        this.dispose();
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_UserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UserNameKeyPressed
        this.txt_UserName.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_txt_UserNameKeyPressed

    private void txt_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PasswordKeyPressed
        this.txt_Password.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_txt_PasswordKeyPressed

    private void txt_PassConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PassConfirmKeyPressed
        this.txt_PassConfirm.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_txt_PassConfirmKeyPressed

    private void txt_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EmailKeyPressed
        this.txt_Email.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_txt_EmailKeyPressed

    private void txt_AddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AddressKeyPressed
        this.txt_Address.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_txt_AddressKeyPressed

    private void txt_MobileNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MobileNumberKeyPressed
        this.txt_MobileNumber.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_txt_MobileNumberKeyPressed

    private void doAddUser() {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Customer customer = new Customer();
        customer.setUsernameC(txt_UserName.getText());
        customer.setPasswordC(String.valueOf(txt_Password.getPassword()));
        customer.setDateOfBirthC(df.format(jdate_DateOfBirthC.getDate()));
        customer.setEmailC(txt_Email.getText());
        customer.setGenderC((String) CbxGender.getSelectedItem());
        customer.setPhoneNumberC(txt_MobileNumber.getText());
        customer.setAddressC(txt_Address.getText());
        cn.InsertAccountCustomer(customer);
        cn.InsertCustomer(customer);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxGender;
    private javax.swing.JButton btn_Cancel1;
    private javax.swing.JButton btn_Cancel2;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdate_DateOfBirthC;
    private javax.swing.JPanel panel_CardLayout;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MobileNumber;
    private javax.swing.JPasswordField txt_PassConfirm;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
